"""
 Hash tables are a type of data structure in which the address or the index value of the data element is generated
 from a hash function. That makes accessing the data faster as the index value behaves as a key for the data value.
 In other words Hash table stores key-value pairs but the key is generated through a hashing function.

 In Python, the Dictionary data types represent the implementation of hash tables. The Keys in the dictionary satisfy
 the following requirements.

    1) The keys of the dictionary are hashable i.e. the are generated by hashing function which generates unique result
     for each unique value supplied to the hash function.
    2) The order of data elements in a dictionary is not fixed.
"""

# Declare a dictionary
dictionary1 = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}
print(dictionary1)

dictionary1['Age'] = 8  # update existing entry
dictionary1['School'] = "DPS School"  # Add new entry
print(dictionary1)

# Accessing the dictionary with its key
print("Name: ", dictionary1['Name'])
print("Age: ", dictionary1['Age'])
print("School: ", dictionary1['School'])

# Delete Dictionary Elements
del dictionary1['School']
print(dictionary1)

dictionary1.clear()
print(dictionary1)

del dictionary1
# print(dictionary1) # it will through the error because dictionary1 has been deleted
